ssec-jhu/evolver-ng

evolver/controller/interface.py, evolver/controller/standard/__init__.py, evolver/controller/standard/chemostat.py, evolver/controller/standard/tests/test_chemostat.py
A first version of the chemostat that roughly follows the chemostat in existing dpu (https://github.com/FYNCH-BIO/dpu/blob/master/experiment/template/custom_script.py#L161), of course without the actual hardware to back it up.
This can serve as an anchor for refactoring and its practical impact on a controller.
=> Add chemostat controller implementation

evolver/connection/interface.py, evolver/serial.py, evolver/tests/test_serial.py
A couple bug fixes. Turns out pyserial implements `is_open` as a property. The exception for bad response hid the response data since the walrus was assigned a boolean.
=> Fix serial is_open check and response exception

evolver/app/main.py, evolver/app/tests/conftest.py, evolver/app/tests/test_app.py, evolver/base.py, evolver/device.py, evolver/settings.py, evolver/util.py
Improvements to #74
Resolves #67 
- Adds ``save`` and ``load`` methods to ``evolver.base.BaseConfig``
- Separate settings for application settings.
- Reading the docs, it's now better to use a lifespan event rather than individual startup and shutdown events.
- Instantiate app ``evolver`` instance on startup, not at module level. (This required #67 to be resolved - see https://github.com/ssec-jhu/evolver-ng/issues/67#issuecomment-2135687714)
See https://github.com/ssec-jhu/evolver-ng/pull/74#issuecomment-2135456108
>I think the files should rep descriptors not just the config such that the file also has the classinfo so that when looking at a config file you know what model it's for.
Also, we should note that ``pydantic`` has similar functionality for reading from files …
=> Post review changes to #74

evolver/app/main.py, evolver/app/tests/conftest.py, evolver/app/tests/test_app.py, evolver/base.py, evolver/connection/interface.py, evolver/controller/interface.py, evolver/controller/standard/chemostat.py, evolver/controller/standard/tests/test_chemostat.py, evolver/device.py, evolver/hardware/demo.py, evolver/hardware/interface.py, evolver/history.py, evolver/serial.py, evolver/settings.py, evolver/tests/test_base.py, evolver/tests/test_device.py, evolver/util.py
Resolves #53
Resolves #67
- This propagates the constructor pattern added in #37 to all other classes.
- adds full init sigs to classes rather than just passing and storing a config.
- unpacks config to actual instance attributes, i.e., internally stuff isn't ref'd by ``self.config.attr`` but ``self.attr``. 
-  add ``*args``, ``**kwargs``, and call to ``super().__init__()`` to allow for inheritance.
- Some extensions to that laid out in #37 have been added.
- Ease of conversion between ``BaseConfig``, ``ConfigDescriptor``, and ``BaseInterface``.
- Add some helper functionality for instantiating nested config descriptors (originally proposed in #35)
- ``config`` & ``descriptor`` properties
=> Refactor usage of creation pattern.

evolver/hardware/standard/od_sensor.py, evolver/hardware/standard/tests/test_od_sensor.py, evolver/serial.py
Part of https://github.com/ssec-jhu/evolver-ng/issues/22
Adds an OD sensor implementation which corresponds to that on the default evolver box. For now the calibration is left out but this shows clearly where it would fit: in providing a value for "density" field of "Output".
Adding also some shared infrastructure for testing these serial-based devices. Probably more of the test infra could be shared for hardware modules, but leaving it specific to OD here.
=> Add initial OD sensor implementation

evolver/base.py, evolver/serial.py, evolver/tests/test_base.py
Discovered during #86 where hardware calibrator descriptors wouldn't get instantiated as they were being converted back to ordinary dictionaries during the nested creation process from ``Evolver.create()``.
=> Only shallow model dump from ConfigDescriptor.create to keep nested descriptors as instances and not dicts

.gitignore, README.md, evolver/app/main.py, scripts/generate_openapi.py, tox.ini
Required if this pipeline for publishing the `evolver-ng-ts-client` npm package is adopted.
We're actually not likely to do this. Instead the generated `openapi.json`will likely be just copied into a `/ui` dir in this project where the frontend will live. The frontend build process (npm) will take care of generating the client from there.
=> add script to generate the openapi.json file

evolver/hardware/standard/pump.py, evolver/hardware/standard/stir.py, evolver/hardware/standard/tests/test_standard.py, evolver/hardware/test_utils.py
Implement stirrer and pumps. 
In the case of stirrer this might not be correct in the case of calibration in that with calibration we might represent rate as RPM, but from the looks of their example experiment code the stirring is practically just used as some rate. Should be straightforward to update since this is a pretty simple effector.
For the pumps, the approach is to model a generic pump that is operates external to vials and indexes on pump number (48 of them), and supports a combination of standard and IPP pumps (these operate in different ways, but communicate to same underlying chip https://github.com/FYNCH-BIO/evolver-arduino/blob/master/SAMD21/RS485_FLUIDICS/RS485_FLUIDICS.ino), and then on top of this implement a per-vial influx/efflux setup that uses a generic device as a …
=> pump and stir

calibration_files/default_temperature_calibration_config.yml, evolver/app/tests/test_app.py, evolver/calibration/interface.py, evolver/calibration/standard/polyfit.py, evolver/calibration/standard/tests/test_fitting.py, evolver/hardware/interface.py, evolver/hardware/standard/temperature.py, evolver/hardware/standard/tests/test_standard.py, evolver/hardware/test_utils.py, evolver/settings.py, evolver/tests/conftest.py, pyproject.toml, requirements/test.txt, scripts/gen_default_cali_files.py
=> 147 call transformers for temp

calibration_files/default_od135_calibration_config.yml, calibration_files/default_od90_calibration_config.yml, calibration_files/default_temperature_calibration_config.yml, evolver/app/tests/test_app.py, evolver/calibration/standard/curve_fit.py, evolver/calibration/standard/polyfit.py, evolver/calibration/standard/tests/test_fitting.py
Resolves #170
This is just a replace-all on ``coefficients`` -> ``parameters``. Only the config description for polyfit keeps a ref to coefficients.
=> Rename Transformer.Config.coefficients -> parameters

evolver/app/routers/hardware.py, evolver/app/tests/test_calibration.py, evolver/app/tests/test_hardware.py, evolver/calibration/actions.py, evolver/calibration/interface.py, tox.ini
There was a mismatch in `check-style` and `format`, where `check-style` passed while format changed some things even in passing case. This means that some things could (and did) get missed which create confusing changes for subsequent PRs.
Only one line is relevent, `tox.ini:17`, everything else is a fix for the style as a result
=> small fix to tox check style to match what format would change

evolver/history/standard.py
This makes history quicker by removing the need to sample files to infer schema. Latency noticeably decreases, but still might want to keep a buffer in memory.
Related to #183, but may only partially resolve
=> Removing sampling for schema in history query

evolver/history/standard.py, evolver/history/tests/test_history.py
This is second of set of changes to make history perform better. For recent data (which should be most common to query) we additionaly store in-memory and query that if possible. Data are always also written out to disk and queryable when not satisfied in memory buffer.
brings UI latency from a couple seconds down to 10s of milliseconds for default query.
Resolves #183
=> [history] Add in-memory buffer of configurable number of partitions

evolver/app/exceptions.py, evolver/app/main.py, evolver/app/routers/hardware.py, evolver/app/tests/test_hardware.py, evolver/hardware/demo.py, evolver/hardware/standard/temperature.py
This change adds endpoints to set hardware inputs from the web api. Adds also some exception handling related to these changes. Along with a smuggled fix for temp inputs.
resolves #181 
**Note**: This allows one to set a value even when the controllers are enabled and might just overwrite it (not guaranteed to be overwritten, just possible). I *think* this is OK here, and any warning should probably be implemented at client level (UI or CLI client), where user interaction is managed.
=> enable setting hardware inputs from web api

evolver/app/main.py, evolver/app/tests/test_app.py, evolver/device.py, evolver/hardware/demo.py, evolver/hardware/interface.py, evolver/hardware/standard/led.py, evolver/hardware/standard/pump.py, evolver/hardware/standard/stir.py, evolver/hardware/standard/temperature.py, evolver/hardware/standard/tests/test_standard.py, evolver/hardware/test_utils.py, evolver/tests/test_device.py
Sets up API for abort, which would put all devices into a stopped state (whatever that means for a particular device still in the powered-on state). The device-level action both stops the control components of loop and also the all devices, while the web-app (application-level) aborts the device and writes out the control disablement to config, such that a restart would not inadvertently continue normal operation without user intervention (given the current mainline behavior of the system)
Resolves #121
=> Add abort api

evolver/app/main.py
HTTP standards demand GET requests do not include a body, all GET params must be passed as query elements.
=> Iainland/refactor history endpoint - split GET and POST handlers

evolver/tests/test_base.py, pyproject.toml, requirements/prd.txt
Relates to #213
This still needs further investigation to determine whether something will remain broken for newer versions of ``pydantic``.  This does not resolve #213, but will temporarily band-aid it.
=> Add nested config test and temp downgrade of pydantic

evolver/app/routers/hardware.py, evolver/app/tests/test_calibration.py, evolver/calibration/action.py, evolver/calibration/procedure.py, evolver/calibration/standard/actions/temperature.py
Adds the input schema to the get actions response. This allows the front end to present the required input UI for the action.
=> extend calibration procedure actions response

evolver/app/main.py, evolver/app/tests/test_app.py, evolver/base.py, evolver/device.py, evolver/history/demo.py, evolver/history/interface.py, evolver/history/standard.py, evolver/history/tests/test_history.py, evolver/logutils.py, evolver/settings.py, evolver/tests/test_logging.py, evolver/util.py
To utilize the existing history server for logs in addition to sensor data, the following steps were taken:
* namespace all included loggers with the package name. This is done so we can modify the logger without affecting root
* add a log handler class that emits to the history API
* add a hookup between the above two within the device manager, along with config options
* modify the history api to take a "kind" and "vial" parameter - kind differentiates between sensor reads and logs, and vial enables logs to be tied to a specific vial
* change shape of sensor data to be row-per-vial, instead of row containing struct of vials (will require corresponding UI mod)
Resolves: #131, Resolves #196
Enables/relates to: #109, #132
Some examples:
```sh
curl -Hcontent-type:application/json -XPOST …
```
=> Hookup for log/event messages to history server

evolver/app/html_routes.py
See screenshot, adds "api documentation" link:
=> add link to api docs to the network endpoint

evolver/logutils.py, evolver/tests/test_logging.py
This change adds user supplied extra fields to the log, via a helper that does namespacing and validation. 
The namespacing is useful since the logger adds all `extra` fields directly to the log record `__dict__`, which ends up making it impossible to find what was added specifically by the user. The helper here adds fields under a specific keyword to keep this context.
The history endpoint also should expect that data are json serializable (in most general cases), so the helper provides facility to do this. 
In general it can be used like:
```py
logger.info('message', extra=LogInfo(vial=1, arbitrary_info='info'))
```
but provides `dump` in case it needs to be spread into other extra data (which spreads fields under the predefined namespace key):
```py
logger.info('message', …
```
=> Log pass through user supplied extra data

.gitignore, evolver/app/routers/hardware.py, evolver/app/tests/test_calibration.py, evolver/calibration/action.py, evolver/calibration/demo.py, evolver/calibration/interface.py, evolver/calibration/procedure.py, evolver/calibration/standard/actions/temperature.py, evolver/calibration/standard/calibrators/temperature.py, evolver/calibration/standard/curve_fit.py, evolver/hardware/standard/pump.py
- The front end must display the current progress of the procedure. This PR adds a "completed_actions" property.
- The front end must support undoing actions. This PR adds an "undo" endpoint".
=> Add procedure completed actions and undo

evolver/app/main.py, evolver/app/tests/test_app.py
FastAPI provides orjson and this looks to be a way that we can allow `NaN` in the json responses. Given passing tests we have some confidence that it produces correct json in other cases.
Resolves #235
=> switch json response handler to enable NaN in serialization

evolver/base.py, evolver/tests/test_base.py, evolver/util.py, tests/test_util.py
#213 Was the main driver for this refactor. However, it does not fix that issue but instead refactors some code to make things more manageable to future changes.
The core change is the creation of ``_BaseModel`` for the separation of conversion back and forth between ``Config``, instances, and ``ConfigDescriptors`` such that it is clearer where in the code this happens - it is no longer circular. For clarity ``_BaseModel`` does not handle the conversion between ``Config`` and ``configDescriptor`` and instead only includes other base conversions, i.e., json strings. Soln. to #234 would also go in this new class. This PR introduces some duplication in logic, but at the expense of it being more direct and explicit per specific desired class behavior.
This should also help and relate to #234.
=> Refactor evolver.base

evolver/device.py, evolver/settings.py, evolver/tests/test_device.py
This adds configuration and validation for a grid layout specification. I'm not sure at the moment how else this needs to be presented or used in the backend, so it is just the configuration for now, which could be used in frontend for presentation.
resolves #153.
=> vial layout

evolver/hardware/demo.py, evolver/hardware/interface.py, evolver/hardware/standard/tests/test_standard.py
Implemented as a configurable fallback value which defaults to `None`
resolves #263
=> falling back to None for uncalibrated values, iso raw value

evolver/app/tests/test_calibration.py, evolver/calibration/interface.py, evolver/calibration/procedure.py, evolver/calibration/standard/calibrators/temperature.py
Keep ongoing/partial procedure state to a separate file to avoid startup conflict with calibration file loading (if specified, the calibration file expects a complete file to load at startup, but the procedure necessarily expects and empty one at start, or a partial one at resume).
Resolves #261
=> separate ongoing procedure file from applied calibration file

evolver/calibration/demo.py, evolver/calibration/interface.py, evolver/calibration/standard/actions/temperature.py, evolver/calibration/standard/calibrators/temperature.py, evolver/hardware/standard/tests/test_temperature_calibrator.py, evolver/tests/test_calibrator.py
This change adds:
* A place to store fitted transformers within the calibration procedure state model, enabling to use the prefit transformers without a refit (in cases where no measured data is stored, or when fitting must be done outside the system).
* A path to detect when to use fitted transformers and automatically apply
* Parameters for default transformers for the multi-vial case. This can be used in the common case where all vials use the same method (each will still be fit with their own parameters)
* Code for at-initialization refit of the temperature calibrator.
I think this resolves or otherwise closes following issues:
* #234 since we can pass via `calibration_file` property now
* #179 since we are committed to working with the files for procedure and loading
* #165 I think …
=> Store fitted calibrator in state model, path to load, and default transformers

evolver/app/main.py, evolver/app/models.py
Updating docstrings on endpoint methods to show up in openapi docs. Adding a few models also for documentation purposes (since fastapi can then report the structure of inputs/outputs)
=> add docstrings for API endpoints, models for better docs

evolver/app/main.py, evolver/app/tests/test_app.py
adds the evolver name to the healthz response. This is so the frontend can use a human-readable name for the device as it exists in the frontend database.
=> add name to healthz endpoint

evolver/hardware/interface.py, evolver/tests/test_hardware_interface.py
I noticed this for a while but was reminded again when working with the pump driver. In some cases we might be working with the model when setting values to hardware, but in other case removing the need to explicitly construct the model is more natural. This enables both:
```py
model = Driver.Input(vial=0, value=1)
hardware.set(model)
```
or 
```py
hardware.set(vial=0, value=1)
```
With this change, these are equivalent (assuming hardware is instance of `Driver`) and both go through model validation.
Comes with some updated doc strings as well
=> update to hardware effector set method

evolver/calibration/procedure.py, evolver/calibration/standard/calibrators/pump.py, evolver/hardware/standard/pump.py, evolver/hardware/standard/tests/test_pump_calibrator.py, evolver/tests/test_logging.py
This PR adds a procedure to the generic pump calibrator, while resolving some minor issues related to the pump necessary for calibration (e.g. setting `time` directly) and adding some conveniences around creating the procedure.
Specifically:
* Lift-and-shift the generic pump calibrator to a module under `standard/calibrators`
* Add the pump calibration procedure, with custom actions
* Update pump input model to take `time` (when `volume` not given)
* Add spec for active pumps on driver (slots refers to total address space, active refers to ones used)
* ~Return `self` in procedure `add_action` enabling operation chaining for readability~
* ~Add `add_action_list` method to procedure, enabling adding list in single chained call~
* Add method for getting an action by name (`get_action(self, …
=> Pump calibration procedure

evolver/calibration/interface.py, evolver/calibration/standard/calibrators/temperature.py
when resuming a calibration procedure, the path the procedure is loaded from using the base config's load method must include the dir for procedure_files.
=> get resume working

evolver/app/tests/test_calibration.py, evolver/calibration/standard/actions/temperature.py, evolver/calibration/standard/calibrators/temperature.py, evolver/hardware/standard/tests/test_temperature_calibrator.py
Two bugs:
* the sensor read action was writing out a struct of the form of `Temperature.Output`, but we really just want the `raw` value from that struct. Corresponding test updated reflecting this
* The "sense" of the fit was backwards, we have advised that convert_to be used in output_transformer for raw to real, but the fit was backwards for this case
Sneaking in also a config to set default output transformer on the temp calibrator to linear fit
=> fix two bugs in temperature calibration

evolver/calibration/standard/actions/temperature.py, evolver/calibration/standard/calibrators/temperature.py, evolver/hardware/standard/temperature.py, evolver/hardware/standard/tests/test_standard.py, evolver/hardware/standard/tests/test_temperature_calibrator.py
This:
* For fist wave: Turns off the heater 
* For all other waves: Sets the heater to a raw adc value proportional to number of steps within a configurable range, relative to the read-in room temperature settings (taken during the first wave). For example:
* if raw reading taken at first wave for vial 0 is `2048`, range `(heater_boundary_low, heater_boundary_high)` is `(0, 1000)`, and `num_temp_readings` is `3`. The second wave for vial 0 will be set at `1548` and the second will be `1048`
* For the temp sensor this corresponds to approximately +10C and +20C for three waves (sensor ~0.02C/unit)
It also fixes the temp driver to allow raw to be set in input
This was modeled after https://github.com/FYNCH-BIO/evolver-electron/blob/master/app/components/TempCalibrate.js, or at least my …
=> Add set temperature action to calibration waves

docs/source/api.rst, docs/source/concepts.rst, docs/source/development/config.rst, docs/source/development/controllers.rst, docs/source/development/hardware.rst, docs/source/development/index.rst, docs/source/development/installation.rst, docs/source/index.rst, docs/source/installation.rst, docs/source/quick-start.rst, docs/source/usage.rst
This PR addresses the below feedback (from slack) in a way I think fits with the package:
> * use "eVOLVER" spelling to maintain consistency (outside of code blocks)
✅ also added a note with disambiguation of use through the docs
> * the config section is still blank but when its populated i think it would useful to show an example of a valid config and the values each attribute expects
> * a page/section dedicated to explaining the core data validation models
^ The first is addressed in the config section pointing to its generic nature and the json schema endpoint/methods, the config class pattern, and the relevant definitions for the application. The second one is addressed in the same config section pointing to its pydantic base and example field definitions.
> * when describing how to …
=> Docs update
