evolver/app/main.py
evolver/app/tests/test_app.py
evolver/base.py
evolver/device.py
evolver/history.py
evolver/tests/test_base.py

Make all config fields required for app update_config path func

---

evolver/app/main.py
evolver/app/tests/conftest.py
evolver/app/tests/test_app.py
evolver/base.py
evolver/device.py
evolver/settings.py
evolver/util.py

Read config file on startup and write upon reconfiguration. ~For the moment the location and whether to write are non-configurable.~
Resolves https://github.com/ssec-jhu/evolver-ng/issues/24
Also sneaks in a change to set host and port for http server via environment variables

Add config file handling in app

---

evolver/__init__.py
evolver/app/main.py
evolver/app/tests/test_app.py
evolver/base.py
evolver/connection/interface.py
evolver/controller/interface.py
evolver/controller/standard/__init__.py
evolver/controller/standard/chemostat.py
evolver/controller/standard/tests/test_chemostat.py
evolver/device.py
evolver/hardware/demo.py
evolver/hardware/interface.py
evolver/history.py
evolver/serial.py
evolver/settings.py
evolver/tests/conftest.py
evolver/tests/test_base.py
evolver/tests/test_device.py
evolver/tests/test_serial.py
evolver/util.py
pyproject.toml
tests/test_util.py
tox.ini

This PR adds the ruff formatter to the project.

Add formatter

---

evolver/app/main.py
evolver/base.py
evolver/settings.py
evolver/tests/test_base.py
evolver/util.py

Resolves #82
This also moves the log level and format to configurable settings.

Don't duplicate log handlers

---

evolver/app/main.py
evolver/app/models.py
evolver/app/tests/test_app.py
evolver/app/tests/test_models.py

Add classinfo query to schema endpoint

---

README.md

fix readme badges to be on single line

---

evolver/hardware/standard/led.py
evolver/hardware/standard/tests/test_standard.py

This adds LED driver (on box this is "od_led") using a 0 to 1 brightness scale and adjustable pwm bit resolution.

LED driver

---

evolver/base.py

Accidentally introduced in #73

Dedupe accidental line copy

---

evolver/connection/interface.py
evolver/controller/interface.py
evolver/controller/standard/chemostat.py
evolver/device.py
evolver/hardware/demo.py
evolver/hardware/interface.py
evolver/hardware/standard/led.py
evolver/hardware/standard/od_sensor.py
evolver/hardware/standard/pump.py
evolver/hardware/standard/stir.py
evolver/hardware/standard/temperature.py
evolver/history.py
evolver/serial.py
evolver/tests/test_base.py

Resolves #104 
This issue is similarly true for ``Input`` and ``Output`` models.

104 Fix container-config inheritance mismatch

---

calibration_files/default_od135_calibration_config.yml
calibration_files/default_od90_calibration_config.yml
evolver/calibration/interface.py
evolver/calibration/standard/curve_fit.py
evolver/calibration/standard/polyfit.py
evolver/calibration/standard/sigmoid.py
evolver/hardware/standard/od_sensor.py
evolver/hardware/standard/temperature.py
evolver/hardware/standard/tests/test_standard.py
evolver/settings.py
pyproject.toml
requirements/prd.txt
scripts/gen_default_cali_files.py

Call transformers for OD

---

evolver/app/tests/test_html.py

Don't test network when testing locally

---

evolver/app/tests/test_html.py
evolver/calibration/interface.py
evolver/controller/standard/chemostat.py
evolver/controller/standard/tests/test_chemostat.py
evolver/hardware/standard/pump.py
evolver/hardware/standard/tests/test_pump_calibrator.py
evolver/hardware/standard/tests/test_standard.py

This adds calibrator for the pumps, at the same time as adds a facility for those to store data in a named "calibration file" which can be used to store user data to refit upon load. This facility is added in the interface so can be reused. I'm not sure with this how to utilize a user-configured transformer (we want a class, not an instance for that), but probably can approach that next.
Also, I had the pump operation wrong, they don't control primarily in flow rate but in injections of volume (and optionally a frequency by which to do the injections). The PR unfortunately includes a bit of distraction refactoring that, sorry 😄

starting on pump transform, but thinking about calibration generally too

---

README.md

Read the docs build is working now, but this closes the loop on #134

add read-the-docs badge to readme

---

docs/source/api.rst
docs/source/concepts.rst

Initial version of the concepts doc that is linked elsewhere. It references a number of classes/methods so adding the API docs to make those links work as well.

Concepts doc

---

.github/dependabot.yml

As noted, due to https://github.com/ssec-jhu/evolver-ng/issues/213, see also https://github.com/ssec-jhu/evolver-ng/pull/219

ignore pydantic for now

---

README.md
tox.ini

adds more convenient commands for running a dev environment. See updated README.md for details.

add tox -e dev command

---

.github/workflows/ci.yml
.github/workflows/dist.yml

fixing upload artifact version to restore CI

---

evolver/calibration/interface.py
evolver/device.py
evolver/tests/test_calibrator.py

clean up some exception handling for clarity

---

docs/source/concepts.rst
docs/source/development/controllers.rst
docs/source/development/hardware.rst
docs/source/index.rst
docs/source/usage.rst

rendered docs for this can be viewed at: https://evolver-ng--279.org.readthedocs.build/en/279/

hardware driver developer docs and other fixes

---

evolver/hardware/interface.py
evolver/tests/test_calibrator.py

fallback in transform on exception
